<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _30_mutasi_model extends CI_Model
{

    public $table = 't30_mutasi';
    public $id = 'idmutasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
    	$this->db->from('t35_alamat');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        // $this->db->order_by($this->id, $this->order);
        // $this->db->like('idmutasi', $q);
    	// $this->db->or_like('idalamat', $q);
    	// $this->db->or_like('tanggal', $q);
    	// $this->db->or_like('Jenis', $q);
    	// $this->db->or_like('idkk', $q);
    	// $this->db->or_like('idusers', $q);
    	// $this->db->or_like('created_at', $q);
    	// $this->db->or_like('updated_at', $q);
        // $this->db->select();
        $q =
            "
            select
            	a.idalamat
                , a.Alamat
                , case when b.Jenis = 'MASUK' then 'Terisi' else 'Kosong' end as Status
                , b.idmutasi
                , b.Nomor
                , b.Nama
            from
            	t35_alamat a
                left join
            		(
                    select
                    	idmutasi
                        , idalamat
                        , a.tanggal
                        , Jenis
                        , a.idkk
                        , b.Nomor
                        , c.Nama
                    from
                    	t30_mutasi a
                        join t07_kk b on a.idkk = b.idkk
                        join t06_penduduk c on b.Nama = c.idpenduduk
                    where
                    	Jenis = 'MASUK'
                        and a.created_at = (select max(created_at) from t30_mutasi group by idalamat having idalamat = a.idalamat)
                    ) b on a.idalamat = b.idalamat
            limit ".$limit." offset ".$start."
            ";
    	// $this->db->limit($limit, $start);
        // echo $q;
        return $this->db->query($q)->result();
        // return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _30_mutasi_model.php */
/* Location: ./application/models/_30_mutasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-19 10:55:53 */
/* http://harviacode.com */
