<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _31_inap_model extends CI_Model
{

    public $table = 't31_inap';
    public $id = 'idinap';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->select($this->table.'.*');
        $this->db->select('t35_alamat.Alamat as AlamatNama');
        $this->db->select('t08_tamu.Nama as TamuNama');
        $this->db->from($this->table);
        $this->db->join('t35_alamat', 't35_alamat.idalamat = '.$this->table.'.Alamat');
        $this->db->join('t08_tamu', 't08_tamu.idtamu = '.$this->table.'.Tamu');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->or_like('t08_tamu.Nama', $q);
        $this->db->or_like('t35_alamat.Alamat', $q);
    	$this->db->or_like('MulaiTanggal', $q);
    	$this->db->or_like('SampaiTanggal', $q);
    	$this->db->or_like('Keperluan', $q);
        $this->db->select($this->table.'.*');
        $this->db->select('t35_alamat.Alamat as AlamatNama');
        $this->db->select('t08_tamu.Nama as TamuNama');
        $this->db->from($this->table);
        $this->db->join('t35_alamat', 't35_alamat.idalamat = '.$this->table.'.Alamat');
        $this->db->join('t08_tamu', 't08_tamu.idtamu = '.$this->table.'.Tamu');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->or_like('t08_tamu.Nama', $q);
        $this->db->or_like('t35_alamat.Alamat', $q);
    	$this->db->or_like('MulaiTanggal', $q);
    	$this->db->or_like('SampaiTanggal', $q);
    	$this->db->or_like('Keperluan', $q);
    	$this->db->limit($limit, $start);
        $this->db->select($this->table.'.*');
        $this->db->select('t35_alamat.Alamat as AlamatNama');
        $this->db->select('t08_tamu.Nama as TamuNama');
        $this->db->from($this->table);
        $this->db->join('t35_alamat', 't35_alamat.idalamat = '.$this->table.'.Alamat');
        $this->db->join('t08_tamu', 't08_tamu.idtamu = '.$this->table.'.Tamu');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _31_inap_model.php */
/* Location: ./application/models/_31_inap_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-20 22:59:48 */
/* http://harviacode.com */
