<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _45_desa_model extends CI_Model
{

    public $table = 't45_desa';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->table.'.'.$this->id, $id);
        $this->db->select($this->table . '.*, t44_kecamatan.nama as kecamatanNama');
        $this->db->from($this->table);
        $this->db->join('t44_kecamatan', 't44_kecamatan.id = '.$this->table.'.kecamatan_id');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->or_like($this->table.'.nama', $q);
        $this->db->or_like('t44_kecamatan.nama', $q);
        $this->db->select($this->table . '.*, t44_kecamatan.nama as kecamatanNama');
        $this->db->from($this->table);
        $this->db->join('t44_kecamatan', 't44_kecamatan.id = '.$this->table.'.kecamatan_id');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
    	$this->db->or_like($this->table.'.nama', $q);
        $this->db->or_like('t44_kecamatan.nama', $q);
    	$this->db->limit($limit, $start);
        $this->db->select($this->table . '.*, t44_kecamatan.nama as kecamatanNama');
        $this->db->from($this->table);
        $this->db->join('t44_kecamatan', 't44_kecamatan.id = '.$this->table.'.kecamatan_id');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // untuk select3 kartu keluarga
    function getData($q)
    {
    	$this->db->like('nama', $q);
        return $this->db->get($this->table)->result();
    }

}

/* End of file _45_desa_model.php */
/* Location: ./application/models/_45_desa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-15 12:43:09 */
/* http://harviacode.com */
