<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _44_kecamatan_model extends CI_Model
{

    public $table = 't44_kecamatan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->table.'.'.$this->id, $id);
        $this->db->select($this->table . '.*, t43_kabupaten.nama as kabupatenNama');
        $this->db->from($this->table);
        $this->db->join('t43_kabupaten', 't43_kabupaten.id = '.$this->table.'.kabupaten_id');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->or_like($this->table.'.nama', $q);
        $this->db->or_like('t43_kabupaten.nama', $q);
        $this->db->select($this->table . '.*, t43_kabupaten.nama as kabupatenNama');
        $this->db->from($this->table);
        $this->db->join('t43_kabupaten', 't43_kabupaten.id = '.$this->table.'.kabupaten_id');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->or_like($this->table.'.nama', $q);
        $this->db->or_like('t43_kabupaten.nama', $q);
    	$this->db->limit($limit, $start);
        $this->db->select($this->table . '.*, t43_kabupaten.nama as kabupatenNama');
        $this->db->from($this->table);
        $this->db->join('t43_kabupaten', 't43_kabupaten.id = '.$this->table.'.kabupaten_id');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // untuk select3 kartu keluarga
    function getData($q)
    {
    	$this->db->like('nama', $q);
        return $this->db->get($this->table)->result();
    }

}

/* End of file _44_kecamatan_model.php */
/* Location: ./application/models/_44_kecamatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-15 12:22:19 */
/* http://harviacode.com */
