<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _06_penduduk_model extends CI_Model
{

    public $table = 't06_penduduk';
    public $id = 'idpenduduk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->select($this->table . '.*');
        $this->db->select('t43_kabupaten.nama as kabupatenNama');
        $this->db->select('t41_agama.Agama as agamaNama');
        $this->db->select('t40_pendidikan.Pendidikan as pendidikanNama');
        $this->db->select('t39_pekerjaan.Pekerjaan as pekerjaanNama');
        $this->db->select('t38_status.Status as statusNama');
        $this->db->select('t37_hubungan.Hubungan as hubunganNama');
        $this->db->select('t36_warganegara.WargaNegara as wargaNegaraNama');
        $this->db->from($this->table);
        $this->db->join('t43_kabupaten', 't43_kabupaten.id = '.$this->table.'.TempatLahir');
        $this->db->join('t41_agama', 't41_agama.idagama = '.$this->table.'.Agama');
        $this->db->join('t40_pendidikan', 't40_pendidikan.idpendidikan = '.$this->table.'.Pendidikan');
        $this->db->join('t39_pekerjaan', 't39_pekerjaan.idpekerjaan = '.$this->table.'.Pekerjaan');
        $this->db->join('t38_status', 't38_status.idstatus = '.$this->table.'.StatusKawin');
        $this->db->join('t37_hubungan', 't37_hubungan.idhubungan = '.$this->table.'.HubunganKeluarga');
        $this->db->join('t36_warganegara', 't36_warganegara.idwarganegara = '.$this->table.'.WargaNegara');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->or_like('NoUrut', $q);
    	$this->db->or_like($this->table.'.Nama', $q);
    	$this->db->or_like('NIK', $q);
    	$this->db->or_like('JenisKelamin', $q);
    	$this->db->or_like('TempatLahir', $q);
    	$this->db->or_like('TanggalLahir', $q);
    	$this->db->or_like('Agama', $q);
    	$this->db->or_like('Pendidikan', $q);
    	$this->db->or_like('Pekerjaan', $q);
    	$this->db->or_like('StatusKawin', $q);
    	$this->db->or_like('HubunganKeluarga', $q);
    	$this->db->or_like('WargaNegara', $q);
    	$this->db->or_like('NoPaspor', $q);
    	$this->db->or_like('NoKitasKitap', $q);
    	$this->db->or_like('NamaAyah', $q);
    	$this->db->or_like('NamaIbu', $q);
        $this->db->or_like('t43_kabupaten.nama', $q);
        $this->db->select($this->table . '.*, t43_kabupaten.nama as kabupatenNama');
        $this->db->from($this->table);
        $this->db->join('t43_kabupaten', 't43_kabupaten.id = '.$this->table.'.TempatLahir');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
    	$this->db->or_like('NoUrut', $q);
    	$this->db->or_like($this->table.'.Nama', $q);
    	$this->db->or_like('NIK', $q);
    	$this->db->or_like('JenisKelamin', $q);
    	$this->db->or_like('TempatLahir', $q);
    	$this->db->or_like('TanggalLahir', $q);
    	$this->db->or_like('Agama', $q);
    	$this->db->or_like('Pendidikan', $q);
    	$this->db->or_like('Pekerjaan', $q);
    	$this->db->or_like('StatusKawin', $q);
    	$this->db->or_like('HubunganKeluarga', $q);
    	$this->db->or_like('WargaNegara', $q);
    	$this->db->or_like('NoPaspor', $q);
    	$this->db->or_like('NoKitasKitap', $q);
    	$this->db->or_like('NamaAyah', $q);
    	$this->db->or_like('NamaIbu', $q);
        $this->db->or_like('t43_kabupaten.nama', $q);
    	$this->db->limit($limit, $start);
        $this->db->select($this->table . '.*, t43_kabupaten.nama as kabupatenNama');
        $this->db->from($this->table);
        $this->db->join('t43_kabupaten', 't43_kabupaten.id = '.$this->table.'.TempatLahir');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // untuk select3 kartu keluarga
    function getData($q)
    {
    	$this->db->like('Nama', $q);
        $this->db->or_like('NIK', $q);
        return $this->db->get($this->table)->result();
    }

}

/* End of file _06_penduduk_model.php */
/* Location: ./application/models/_06_penduduk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-15 16:59:40 */
/* http://harviacode.com */
